# Vorgabewerte f√ºr das Elexis-Cockpit
---
# If you have MySQL backups named like
# /home/backup/mysql/mysql_backup_20130310-230501.sql.bz2
# set the next two lines like
elexis::db_backup::dir: /home/backup
elexis::url: Elexis/URL
# To we use MySQL or Postgres ?
elexis::db_type: mysql

# Elexis-Vagrant puts all custom binaries into /usr/local/bin
elexis::install::script: /usr/local/bin/install_elexis.rb

# These are the default values for MySQL
elexis::db_mysql::switch::script: /usr/local/bin/mysql_switch_db_server.rb
elexis::db_mysql::dump::script: /usr/local/bin/mysql_dump_elexis.rb
elexis::db_mysql::load::script: /usr/local/bin/mysql_load_elexis.rb
elexis::db_mysql::backup::files: /home/backup/mysql/mysql_backup_*.sql.bz2

# These are the default values for PostgreSQL
elexis::db_postgresql::switch::script: /usr/local/bin/pg_switch_db_server.rb
elexis::db_postgresql::load::script: /usr/local/bin/pg_load_elexis.rb
elexis::db_postgresql::dump::script: /usr/local/bin/pg_dump_elexis.rb
elexis::db_postgresql::backup::files: /home/backup/pg/pg_backup_*.sql.bz2

# Name of first DB-server
elexis::db_server: server_1_green

# Name of second DB-server
elexis::db_backup: server_2_orange

# Tell who is the backup DB server (or false) if there is no online backup
elexis::db_server::backup_server_is: server_2_orange
elexis::db_port: 3306
elexis::db_user: elexis
elexis::db_main: elexis

# Scripts to format and encrypt external HD disk
elexis::hd::external::format_and_encrypt: /usr/local/bin/backup_encrypted.rb
elexis::hd::external::keyfile: /home/backup/external/id.sdd

elexis::server::reboot::script: '/usr/local/bin/reboot'
elexis::server::halt::script: '/usr/local/bin/halt'
