# Vorgabewerte f√ºr das Elexis-Cockpit
---
# If you have MySQL backups named like
# /home/backup/mysql/mysql_backup_20130310-230501.sql.bz2
# set the next two lines like
elexis::db_backup_dir: /home/backup
elexis::url: Elexis/URL
# To we use MySQL or Postgres ?
elexis::db_type: mysql

# Scripts to format and encrypt external HD disk
elexis::hd_external_format_and_encrypt: /usr/local/bin/backup_encrypted.rb
elexis::hd_external_keyfile: /home/backup/external/id.sdd

# This script must be normal bash scripts or we will have problem
elexis::install_script: /usr/local/bin/install_elexis
server::reboot_script: /usr/local/bin/reboot.sh
server::halt_script:   /usr/local/bin/halt.sh

# Elexis-Vagrant puts all custom binaries into /usr/local/bin
elexis::install_script: /usr/local/bin/install_elexis.rb

# These are the default values for MySQL
elexis::mysql_main_db_name:     elexis
elexis::mysql_tst_db_name:      test
elexis::mysql_main_db_user:     elexis
elexis::mysql_main_db_password: elexisTest
# here goes the dump of mysql DB
elexis::mysql_dump_dir:         /opt/backup/mysql/dumps
# here goes the backups of the dumps of mysql DB
elexis::mysql_backup_dir:       /opt/backup/mysql/backups
elexis::mysql_backup_files:     /opt/backup/mysql/*/elexis.dump*.gz

# These are the default values for PostgreSQL
# here goes the dump of postres DB
elexis::pg_dump_dir:            /opt/backup/pg/dumps/
# here goes the backups of the dumps of postres DB
elexis::pg_backup_dir:          /opt/backup/pg/backups/
elexis::pg_backup_files:        /opt/backup/pg/*/pg_backup_*.sql
# next lines must be in sync with dbs
elexis::pg_main_db_name:     elexis
elexis::pg_tst_db_name:      test
elexis::pg_main_db_user:     elexis
elexis::pg_main_db_password: elexisTest

# Name of first DB-server
elexis::db_server: server_1_green

# Name of second DB-server
elexis::db_backup: server_2_orange

# Tell who is the backup DB server (or false) if there is no online backup
elexis::db_server::backup_server_is: server_2_orange
elexis::db_port: 3306
elexis::db_user: elexis
elexis::db_main: elexis

